"""
Missing Age/Gender Finder Tool - Cloud Vision Version
For Excel files generated by voter_counter_cloud_vision.py

Excel Format:
- S.No: Serial number from OCR (printed on card)
- Part No.: PDF part number
- Page No.: Page number in PDF (for image reference)
- Voter ID, Name, etc.
- PDF Name: Full PDF filename (for folder reference)

Image Location:
- .{constituency}_cloud_pages/{PDF Name}/page_{Page No.}.png
- These are FULL PAGE images (~30 cards per page)

Features:
- Shows full page image with card location hint
- Displays card info (S.No, Voter ID, Name) to help locate on page
- Manual entry for missing Age/Gender
- OCR retry on cropped region
- Save updates back to Excel
"""

import tkinter as tk
from tkinter import ttk, filedialog, messagebox
from pathlib import Path
import subprocess
import re

# Install dependencies
def install_packages():
    packages = ['openpyxl', 'pillow', 'pytesseract']
    for pkg in packages:
        try:
            __import__(pkg.replace('-', '_'))
        except ImportError:
            print(f"Installing {pkg}...")
            subprocess.check_call(['uv', 'pip', 'install', pkg])

install_packages()

from openpyxl import load_workbook
from openpyxl.styles import PatternFill
from PIL import Image, ImageTk, ImageDraw, ImageEnhance

try:
    import pytesseract
except ImportError:
    subprocess.check_call(['uv', 'pip', 'install', 'pytesseract'])
    import pytesseract

TESSERACT_CONFIG = '--psm 6 --oem 1'


class MissingDataFinderCloud:
    def __init__(self, root):
        self.root = root
        self.root.title("Missing Age/Gender Finder - Cloud Vision")
        self.root.geometry("1400x900")
        self.root.resizable(True, True)

        # Data
        self.excel_path = None
        self.workbook = None
        self.worksheet = None
        self.image_folder = None
        self.missing_rows = []
        self.current_index = 0
        self.current_image = None
        self.current_pil_image = None
        self.changes_made = False

        self.style = ttk.Style()
        self.style.configure('Title.TLabel', font=('Helvetica', 14, 'bold'))
        self.style.configure('Header.TLabel', font=('Helvetica', 11, 'bold'))
        self.style.configure('Big.TButton', font=('Helvetica', 12))
        self.style.configure('Highlight.TLabel', font=('Helvetica', 12, 'bold'), foreground='#E91E63')

        self.create_widgets()

    def create_widgets(self):
        # Main container
        main_frame = ttk.Frame(self.root, padding="10")
        main_frame.pack(fill=tk.BOTH, expand=True)

        # Top section - File selection
        file_frame = ttk.LabelFrame(main_frame, text="File Selection", padding="10")
        file_frame.pack(fill=tk.X, pady=(0, 10))

        # Excel file row
        excel_row = ttk.Frame(file_frame)
        excel_row.pack(fill=tk.X, pady=2)
        ttk.Label(excel_row, text="Excel File:", width=12).pack(side=tk.LEFT)
        self.excel_path_var = tk.StringVar()
        ttk.Entry(excel_row, textvariable=self.excel_path_var, width=80).pack(side=tk.LEFT, padx=5)
        ttk.Button(excel_row, text="Browse...", command=self.browse_excel).pack(side=tk.LEFT, padx=5)
        ttk.Button(excel_row, text="Load", command=self.load_excel).pack(side=tk.LEFT, padx=5)

        # Image folder row
        img_row = ttk.Frame(file_frame)
        img_row.pack(fill=tk.X, pady=2)
        ttk.Label(img_row, text="Image Folder:", width=12).pack(side=tk.LEFT)
        self.image_folder_var = tk.StringVar()
        ttk.Entry(img_row, textvariable=self.image_folder_var, width=80).pack(side=tk.LEFT, padx=5)
        ttk.Button(img_row, text="Browse...", command=self.browse_image_folder).pack(side=tk.LEFT, padx=5)

        # Stats row
        stats_row = ttk.Frame(file_frame)
        stats_row.pack(fill=tk.X, pady=(5, 0))
        self.stats_var = tk.StringVar(value="No file loaded")
        ttk.Label(stats_row, textvariable=self.stats_var, foreground='#2196F3').pack(side=tk.LEFT)

        # Middle section - Split view
        content_frame = ttk.Frame(main_frame)
        content_frame.pack(fill=tk.BOTH, expand=True, pady=10)

        # Left panel - Missing rows list
        left_frame = ttk.LabelFrame(content_frame, text="Missing Age/Gender Rows", padding="5")
        left_frame.pack(side=tk.LEFT, fill=tk.BOTH, expand=False, padx=(0, 5))

        # List with scrollbar
        list_container = ttk.Frame(left_frame)
        list_container.pack(fill=tk.BOTH, expand=True)

        self.row_listbox = tk.Listbox(list_container, width=45, height=20, font=('Courier', 9))
        scrollbar = ttk.Scrollbar(list_container, orient=tk.VERTICAL, command=self.row_listbox.yview)
        self.row_listbox.configure(yscrollcommand=scrollbar.set)

        self.row_listbox.pack(side=tk.LEFT, fill=tk.BOTH, expand=True)
        scrollbar.pack(side=tk.RIGHT, fill=tk.Y)

        self.row_listbox.bind('<<ListboxSelect>>', self.on_row_select)

        # Filter options
        filter_frame = ttk.Frame(left_frame)
        filter_frame.pack(fill=tk.X, pady=(5, 0))

        self.filter_var = tk.StringVar(value="all")
        ttk.Radiobutton(filter_frame, text="All", variable=self.filter_var,
                       value="all", command=self.apply_filter).pack(side=tk.LEFT)
        ttk.Radiobutton(filter_frame, text="Age", variable=self.filter_var,
                       value="age", command=self.apply_filter).pack(side=tk.LEFT)
        ttk.Radiobutton(filter_frame, text="Gender", variable=self.filter_var,
                       value="gender", command=self.apply_filter).pack(side=tk.LEFT)

        # Right panel - Image and editor
        right_frame = ttk.Frame(content_frame)
        right_frame.pack(side=tk.LEFT, fill=tk.BOTH, expand=True, padx=(5, 0))

        # Card info panel (highlight to help find on page)
        card_info_frame = ttk.LabelFrame(right_frame, text="Find This Card on Page", padding="10")
        card_info_frame.pack(fill=tk.X, pady=(0, 5))

        info_grid = ttk.Frame(card_info_frame)
        info_grid.pack(fill=tk.X)

        ttk.Label(info_grid, text="S.No:", style='Header.TLabel').grid(row=0, column=0, sticky=tk.W, padx=5)
        self.sno_var = tk.StringVar(value="--")
        ttk.Label(info_grid, textvariable=self.sno_var, style='Highlight.TLabel').grid(row=0, column=1, sticky=tk.W, padx=5)

        ttk.Label(info_grid, text="Voter ID:", style='Header.TLabel').grid(row=0, column=2, sticky=tk.W, padx=5)
        self.voter_id_var = tk.StringVar(value="--")
        ttk.Label(info_grid, textvariable=self.voter_id_var, style='Highlight.TLabel').grid(row=0, column=3, sticky=tk.W, padx=5)

        ttk.Label(info_grid, text="Name:", style='Header.TLabel').grid(row=0, column=4, sticky=tk.W, padx=5)
        self.name_var = tk.StringVar(value="--")
        ttk.Label(info_grid, textvariable=self.name_var, foreground='#2196F3',
                 font=('Helvetica', 11)).grid(row=0, column=5, sticky=tk.W, padx=5)

        # Page info
        page_info_frame = ttk.Frame(card_info_frame)
        page_info_frame.pack(fill=tk.X, pady=(5, 0))

        ttk.Label(page_info_frame, text="Part:").pack(side=tk.LEFT)
        self.part_var = tk.StringVar(value="--")
        ttk.Label(page_info_frame, textvariable=self.part_var, foreground='#4CAF50',
                 font=('Helvetica', 10, 'bold')).pack(side=tk.LEFT, padx=(2, 15))

        ttk.Label(page_info_frame, text="Page:").pack(side=tk.LEFT)
        self.page_var = tk.StringVar(value="--")
        ttk.Label(page_info_frame, textvariable=self.page_var, foreground='#4CAF50',
                 font=('Helvetica', 10, 'bold')).pack(side=tk.LEFT, padx=(2, 15))

        ttk.Label(page_info_frame, text="Image:").pack(side=tk.LEFT)
        self.image_path_var = tk.StringVar(value="--")
        ttk.Label(page_info_frame, textvariable=self.image_path_var, foreground='#9C27B0',
                 font=('Helvetica', 9)).pack(side=tk.LEFT, padx=2)

        # Image display with scroll
        image_frame = ttk.LabelFrame(right_frame, text="Page Image (scroll to find card)", padding="5")
        image_frame.pack(fill=tk.BOTH, expand=True)

        # Canvas with scrollbars for large page images
        self.canvas = tk.Canvas(image_frame, bg='white')
        h_scroll = ttk.Scrollbar(image_frame, orient=tk.HORIZONTAL, command=self.canvas.xview)
        v_scroll = ttk.Scrollbar(image_frame, orient=tk.VERTICAL, command=self.canvas.yview)
        self.canvas.configure(xscrollcommand=h_scroll.set, yscrollcommand=v_scroll.set)

        h_scroll.pack(side=tk.BOTTOM, fill=tk.X)
        v_scroll.pack(side=tk.RIGHT, fill=tk.Y)
        self.canvas.pack(side=tk.LEFT, fill=tk.BOTH, expand=True)

        # Mouse wheel scrolling
        self.canvas.bind('<MouseWheel>', lambda e: self.canvas.yview_scroll(-1*(e.delta//120), 'units'))
        self.canvas.bind('<Shift-MouseWheel>', lambda e: self.canvas.xview_scroll(-1*(e.delta//120), 'units'))

        # Editor panel
        editor_frame = ttk.LabelFrame(right_frame, text="Enter Missing Data", padding="10")
        editor_frame.pack(fill=tk.X, pady=(5, 0))

        # Age and Gender inputs
        input_row = ttk.Frame(editor_frame)
        input_row.pack(fill=tk.X, pady=5)

        # Age input
        age_frame = ttk.Frame(input_row)
        age_frame.pack(side=tk.LEFT, padx=(0, 30))

        ttk.Label(age_frame, text="Age:", style='Header.TLabel').pack(side=tk.LEFT)
        self.age_var = tk.StringVar()
        self.age_entry = ttk.Entry(age_frame, textvariable=self.age_var, width=10, font=('Helvetica', 14))
        self.age_entry.pack(side=tk.LEFT, padx=5)

        self.age_status_var = tk.StringVar(value="")
        ttk.Label(age_frame, textvariable=self.age_status_var, foreground='#F44336').pack(side=tk.LEFT)

        # Gender input
        gender_frame = ttk.Frame(input_row)
        gender_frame.pack(side=tk.LEFT, padx=(0, 30))

        ttk.Label(gender_frame, text="Gender:", style='Header.TLabel').pack(side=tk.LEFT)
        self.gender_var = tk.StringVar()
        self.gender_combo = ttk.Combobox(gender_frame, textvariable=self.gender_var,
                                         values=['', 'Male', 'Female'], width=10, font=('Helvetica', 14))
        self.gender_combo.pack(side=tk.LEFT, padx=5)

        self.gender_status_var = tk.StringVar(value="")
        ttk.Label(gender_frame, textvariable=self.gender_status_var, foreground='#F44336').pack(side=tk.LEFT)

        # Quick gender buttons
        ttk.Button(input_row, text="M", command=lambda: self.gender_var.set('Male'), width=3).pack(side=tk.LEFT, padx=2)
        ttk.Button(input_row, text="F", command=lambda: self.gender_var.set('Female'), width=3).pack(side=tk.LEFT, padx=2)

        # Buttons row
        btn_row = ttk.Frame(editor_frame)
        btn_row.pack(fill=tk.X, pady=(10, 5))

        ttk.Button(btn_row, text="< Prev", command=self.prev_row, width=8).pack(side=tk.LEFT, padx=2)
        ttk.Button(btn_row, text="Next >", command=self.next_row, width=8).pack(side=tk.LEFT, padx=2)

        ttk.Button(btn_row, text="Apply", command=self.apply_changes, width=10).pack(side=tk.LEFT, padx=10)
        ttk.Button(btn_row, text="Apply & Next", command=self.apply_and_next, width=12).pack(side=tk.LEFT, padx=2)

        ttk.Button(btn_row, text="Zoom In", command=self.zoom_in, width=8).pack(side=tk.LEFT, padx=10)
        ttk.Button(btn_row, text="Zoom Out", command=self.zoom_out, width=8).pack(side=tk.LEFT, padx=2)

        # Bottom section - Save
        bottom_frame = ttk.Frame(main_frame)
        bottom_frame.pack(fill=tk.X, pady=(10, 0))

        self.progress_var = tk.StringVar(value="0/0")
        ttk.Label(bottom_frame, textvariable=self.progress_var, font=('Helvetica', 12, 'bold')).pack(side=tk.LEFT)

        ttk.Button(bottom_frame, text="Save Excel", command=self.save_excel,
                  style='Big.TButton').pack(side=tk.RIGHT, padx=5)

        self.save_status_var = tk.StringVar(value="")
        ttk.Label(bottom_frame, textvariable=self.save_status_var, foreground='#4CAF50').pack(side=tk.RIGHT, padx=10)

        # Keyboard shortcuts
        self.root.bind('<Left>', lambda e: self.prev_row())
        self.root.bind('<Right>', lambda e: self.next_row())
        self.root.bind('<Return>', lambda e: self.apply_and_next())
        self.root.bind('<Control-s>', lambda e: self.save_excel())
        self.root.bind('<m>', lambda e: self.gender_var.set('Male'))
        self.root.bind('<f>', lambda e: self.gender_var.set('Female'))
        self.root.bind('<plus>', lambda e: self.zoom_in())
        self.root.bind('<minus>', lambda e: self.zoom_out())

        # Zoom level
        self.zoom_level = 1.0

    def browse_excel(self):
        file_path = filedialog.askopenfilename(
            title="Select Cloud Vision Excel File",
            filetypes=[("Excel files", "*_cloud_excel.xlsx"), ("All Excel", "*.xlsx")]
        )
        if file_path:
            self.excel_path_var.set(file_path)

            # Auto-detect image folder
            excel_path = Path(file_path)
            parent = excel_path.parent

            # Try to find cloud_pages folder
            constituency_name = excel_path.stem.replace('_cloud_excel', '')
            possible_folders = [
                parent / f".{constituency_name}_cloud_pages",
                parent / f"{constituency_name}_cloud_pages",
            ]

            for folder in possible_folders:
                if folder.exists():
                    self.image_folder_var.set(str(folder))
                    break

    def browse_image_folder(self):
        folder = filedialog.askdirectory(title="Select Cloud Pages Image Folder")
        if folder:
            self.image_folder_var.set(folder)

    def load_excel(self):
        excel_path = self.excel_path_var.get()
        if not excel_path or not Path(excel_path).exists():
            messagebox.showerror("Error", "Please select a valid Excel file.")
            return

        image_folder = self.image_folder_var.get()
        if not image_folder or not Path(image_folder).exists():
            messagebox.showwarning("Warning", "Image folder not found. Images won't be displayed.")
            self.image_folder = None
        else:
            self.image_folder = Path(image_folder)

        try:
            self.excel_path = Path(excel_path)
            self.workbook = load_workbook(self.excel_path)
            self.worksheet = self.workbook.active

            # Find missing rows
            self.find_missing_rows()

            # Update stats
            total_rows = self.worksheet.max_row - 1
            missing_count = len(self.missing_rows)
            self.stats_var.set(f"Loaded: {total_rows:,} rows | Missing: {missing_count:,}")

            # Populate list
            self.apply_filter()

            if missing_count > 0:
                self.row_listbox.selection_set(0)
                self.on_row_select(None)

        except Exception as e:
            messagebox.showerror("Error", f"Failed to load Excel: {e}")
            import traceback
            traceback.print_exc()

    def find_missing_rows(self):
        """Find all rows with missing Age or Gender."""
        self.missing_rows = []

        # Cloud Vision Excel columns (1-based):
        # 1:S.No, 2:Part No., 3:Page No., 4:Voter ID, 5:Name, 6:Relation Type,
        # 7:Relation Name, 8:House No, 9:Age, 10:Gender, 11:Constituency, 12:PDF Name
        sno_col = 1
        part_col = 2
        page_col = 3
        voter_id_col = 4
        name_col = 5
        age_col = 9
        gender_col = 10
        pdf_name_col = 12

        for row_num in range(2, self.worksheet.max_row + 1):
            sno_val = self.worksheet.cell(row=row_num, column=sno_col).value
            part_no = self.worksheet.cell(row=row_num, column=part_col).value
            page_no = self.worksheet.cell(row=row_num, column=page_col).value
            voter_id = self.worksheet.cell(row=row_num, column=voter_id_col).value
            name = self.worksheet.cell(row=row_num, column=name_col).value
            age_val = self.worksheet.cell(row=row_num, column=age_col).value
            gender_val = self.worksheet.cell(row=row_num, column=gender_col).value
            pdf_name = self.worksheet.cell(row=row_num, column=pdf_name_col).value

            age_missing = not age_val or str(age_val).strip() == ''
            gender_missing = not gender_val or str(gender_val).strip() == ''

            if age_missing or gender_missing:
                self.missing_rows.append({
                    'row_num': row_num,
                    'sno': sno_val or '',
                    'part_no': str(part_no) if part_no else '',
                    'page_no': str(page_no) if page_no else '',
                    'voter_id': voter_id or '',
                    'name': name or '',
                    'pdf_name': pdf_name or '',
                    'age': age_val or '',
                    'gender': gender_val or '',
                    'age_missing': age_missing,
                    'gender_missing': gender_missing
                })

    def apply_filter(self):
        """Apply filter and update listbox."""
        self.row_listbox.delete(0, tk.END)

        filter_type = self.filter_var.get()

        for i, row_data in enumerate(self.missing_rows):
            if filter_type == 'age' and not row_data['age_missing']:
                continue
            if filter_type == 'gender' and not row_data['gender_missing']:
                continue

            # Format: Row | Part | Page | S.No | Missing
            age_status = '?' if row_data['age_missing'] else 'OK'
            gender_status = '?' if row_data['gender_missing'] else 'OK'

            display = f"R{row_data['row_num']:4d} P{row_data['part_no']:>2s} Pg{row_data['page_no']:>3s} S{row_data['sno']:>3s} A:{age_status} G:{gender_status}"
            self.row_listbox.insert(tk.END, display)

            # Color code
            if row_data['age_missing'] and row_data['gender_missing']:
                self.row_listbox.itemconfig(tk.END, fg='#F44336')  # Red
            elif row_data['age_missing']:
                self.row_listbox.itemconfig(tk.END, fg='#FF9800')  # Orange
            else:
                self.row_listbox.itemconfig(tk.END, fg='#9C27B0')  # Purple

        self.update_progress()

    def update_progress(self):
        """Update progress display."""
        total = len(self.missing_rows)
        fixed = sum(1 for r in self.missing_rows if not r['age_missing'] and not r['gender_missing'])
        self.progress_var.set(f"Fixed: {fixed}/{total}")

    def on_row_select(self, event):
        """Handle row selection in listbox."""
        selection = self.row_listbox.curselection()
        if not selection:
            return

        index = selection[0]

        # Map listbox index to missing_rows index based on filter
        filter_type = self.filter_var.get()
        filtered_indices = []

        for i, row_data in enumerate(self.missing_rows):
            if filter_type == 'age' and not row_data['age_missing']:
                continue
            if filter_type == 'gender' and not row_data['gender_missing']:
                continue
            filtered_indices.append(i)

        if index < len(filtered_indices):
            self.current_index = filtered_indices[index]
            self.display_current_row()

    def display_current_row(self):
        """Display the current row's page image and data."""
        if not self.missing_rows or self.current_index >= len(self.missing_rows):
            return

        row_data = self.missing_rows[self.current_index]

        # Update card info
        self.sno_var.set(row_data['sno'])
        self.voter_id_var.set(row_data['voter_id'])
        self.name_var.set(row_data['name'][:30] + '...' if len(row_data['name']) > 30 else row_data['name'])
        self.part_var.set(row_data['part_no'])
        self.page_var.set(row_data['page_no'])

        # Image path
        if row_data['pdf_name'] and row_data['page_no']:
            img_path = f"{row_data['pdf_name']}/page_{row_data['page_no']}.png"
            self.image_path_var.set(img_path[:60] + '...' if len(img_path) > 60 else img_path)
        else:
            self.image_path_var.set("--")

        # Update input fields
        self.age_var.set(row_data['age'])
        self.gender_var.set(row_data['gender'])

        # Update status indicators
        self.age_status_var.set("MISSING" if row_data['age_missing'] else "")
        self.gender_status_var.set("MISSING" if row_data['gender_missing'] else "")

        # Load page image
        self.load_page_image(row_data['pdf_name'], row_data['page_no'])

    def load_page_image(self, pdf_name, page_no):
        """Load and display the page image."""
        self.canvas.delete("all")

        if not self.image_folder or not pdf_name or not page_no:
            self.canvas.create_text(400, 300, text="Image folder or page info not available",
                                   font=('Helvetica', 14))
            return

        # Construct image path
        image_path = self.image_folder / pdf_name / f"page_{page_no}.png"

        if not image_path.exists():
            self.canvas.create_text(400, 300,
                                   text=f"Image not found:\n{image_path}",
                                   font=('Helvetica', 12), justify=tk.CENTER)
            return

        try:
            # Load image
            self.current_pil_image = Image.open(image_path)

            # Apply zoom
            width = int(self.current_pil_image.width * self.zoom_level)
            height = int(self.current_pil_image.height * self.zoom_level)

            img_resized = self.current_pil_image.resize((width, height), Image.LANCZOS)

            # Convert to PhotoImage
            self.current_image = ImageTk.PhotoImage(img_resized)

            # Update canvas
            self.canvas.config(scrollregion=(0, 0, width, height))
            self.canvas.create_image(0, 0, anchor=tk.NW, image=self.current_image)

        except Exception as e:
            self.canvas.create_text(400, 300, text=f"Error loading image:\n{e}",
                                   font=('Helvetica', 12), justify=tk.CENTER)

    def zoom_in(self):
        """Zoom in on the image."""
        self.zoom_level = min(3.0, self.zoom_level + 0.25)
        if self.missing_rows and self.current_index < len(self.missing_rows):
            row_data = self.missing_rows[self.current_index]
            self.load_page_image(row_data['pdf_name'], row_data['page_no'])

    def zoom_out(self):
        """Zoom out on the image."""
        self.zoom_level = max(0.25, self.zoom_level - 0.25)
        if self.missing_rows and self.current_index < len(self.missing_rows):
            row_data = self.missing_rows[self.current_index]
            self.load_page_image(row_data['pdf_name'], row_data['page_no'])

    def apply_changes(self):
        """Apply changes to the current row."""
        if not self.missing_rows or self.current_index >= len(self.missing_rows):
            return

        row_data = self.missing_rows[self.current_index]
        row_num = row_data['row_num']

        age_val = self.age_var.get().strip()
        gender_val = self.gender_var.get().strip()

        # Validate age
        if age_val:
            try:
                age_int = int(age_val)
                if age_int < 18 or age_int > 120:
                    messagebox.showwarning("Warning", "Age should be between 18 and 120")
                    return
            except ValueError:
                messagebox.showerror("Error", "Age must be a number")
                return

        # Update worksheet (Cloud Vision format: Age=9, Gender=10)
        self.worksheet.cell(row=row_num, column=9, value=age_val if age_val else None)
        self.worksheet.cell(row=row_num, column=10, value=gender_val if gender_val else None)

        # Remove yellow fill if data is now complete
        if age_val:
            self.worksheet.cell(row=row_num, column=9).fill = PatternFill()
        if gender_val:
            self.worksheet.cell(row=row_num, column=10).fill = PatternFill()

        # Update tracking
        row_data['age'] = age_val
        row_data['gender'] = gender_val
        row_data['age_missing'] = not age_val
        row_data['gender_missing'] = not gender_val

        self.changes_made = True
        self.save_status_var.set("Unsaved changes")

        # Update display
        self.age_status_var.set("" if age_val else "MISSING")
        self.gender_status_var.set("" if gender_val else "MISSING")

        # Refresh list
        self.apply_filter()
        self.highlight_current_in_list()

    def apply_and_next(self):
        """Apply changes and move to next row."""
        self.apply_changes()
        self.next_row()

    def prev_row(self):
        """Go to previous row."""
        if self.current_index > 0:
            self.current_index -= 1
            self.display_current_row()
            self.highlight_current_in_list()

    def next_row(self):
        """Go to next row."""
        if self.current_index < len(self.missing_rows) - 1:
            self.current_index += 1
            self.display_current_row()
            self.highlight_current_in_list()

    def highlight_current_in_list(self):
        """Highlight current row in listbox."""
        filter_type = self.filter_var.get()
        list_index = 0

        for i, row_data in enumerate(self.missing_rows):
            if filter_type == 'age' and not row_data['age_missing']:
                continue
            if filter_type == 'gender' and not row_data['gender_missing']:
                continue

            if i == self.current_index:
                self.row_listbox.selection_clear(0, tk.END)
                self.row_listbox.selection_set(list_index)
                self.row_listbox.see(list_index)
                break

            list_index += 1

    def save_excel(self):
        """Save changes to Excel file."""
        if not self.workbook:
            messagebox.showwarning("Warning", "No Excel file loaded")
            return

        try:
            # Create backup
            backup_path = self.excel_path.with_suffix('.xlsx.bak')
            if self.excel_path.exists():
                import shutil
                shutil.copy(self.excel_path, backup_path)

            # Save
            self.workbook.save(self.excel_path)

            self.changes_made = False
            self.save_status_var.set(f"Saved! Backup: {backup_path.name}")

            # Count remaining missing
            remaining = sum(1 for r in self.missing_rows if r['age_missing'] or r['gender_missing'])
            messagebox.showinfo("Saved", f"Excel saved successfully!\n\nRemaining missing: {remaining}")

        except Exception as e:
            messagebox.showerror("Error", f"Failed to save:\n{e}")

    def on_closing(self):
        """Handle window close."""
        if self.changes_made:
            result = messagebox.askyesnocancel(
                "Unsaved Changes",
                "You have unsaved changes. Save before closing?"
            )
            if result is None:
                return
            elif result:
                self.save_excel()

        self.root.destroy()


def main():
    root = tk.Tk()
    app = MissingDataFinderCloud(root)
    root.protocol("WM_DELETE_WINDOW", app.on_closing)
    root.mainloop()


if __name__ == "__main__":
    main()
